export const searchData = [
  {
    title: "Home",
    description: "Go to the welcome page",
    path: "/",
    keywords: [
      "home",
      "cv",
      "resume",
      "start",
      "welcome",
      "portfolio",
      "tushar",
      "tushar kumar",
      "mern developer",
      "full stack developer",
      "mern stack",
      "web developer",
    ],
  },
  {
    title: "About",
    description: "Learn more about me and my background",
    path: "/about",
    keywords: [
      "about",
      "background",
      "education",
      "bio",
      "profile",
      "cv",
      "resume",
      "tushar",
      "kumar",
      "full stack developer",
      "mca graduate",
      "web developer",
    ],
  },
  {
    title: "Education",
    description: "View my educational background",
    path: "/education",
    keywords: [
      "education",
      "university",
      "college",
      "degree",
      "school",
      "mca",
      "bca",
      "meerut institute of engineering and technology",
      "miet",
      "forte institute of technology",
    ],
  },
  {
    title: "Experience",
    description: "Check out my professional experience",
    path: "/experience",
    keywords: [
      "experience",
      "work",
      "career",
      "jobs",
      "professional",
      "acciojob",
      "trainee",
      "mern",
      "full stack",
      "software developer",
    ],
  },
  {
    title: "Skills",
    description: "Explore my technical skills and expertise",
    path: "/skills",
    keywords: [
      "skills",
      "technologies",
      "programming",
      "frameworks",
      "react",
      "node",
      "javascript",
      "typescript",
      "nextjs",
      "mongodb",
      "sql",
    ],
  },
  {
    title: "Projects",
    description: "View my portfolio of projects",
    path: "/projects",
    keywords: [
      "projects",
      "portfolio",
      "github",
      "code",
      "opensource",
      "react",
      "node",
      "mern",
      "swaadly",
      "food delivery",
      "lms",
      "learning management system",
      "hqmovies",
      "movie app",
    ],
  },
  {
    title: "Certificates",
    description: "View my certifications and achievements",
    path: "/certificates",
    keywords: [
      "certificates",
      "certifications",
      "achievements",
      "courses",
      "learning",
      "awards",
      "badges",
    ],
  },
];
